version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: Scripts/before_install.sh
      timeout: 100
      runas: root

  AfterInstall:
    - location: Scripts/after_install.sh
      timeout: 100
      runas: root

  ApplicationStart:
    - location: Scripts/app_start.sh
      timeout: 100
      runas: root
